# Site settings
title: Genome Sequence database for the human gut microbiome
email: leo.lahti@iki.fi
description: > # this means to ignore newlines until "baseurl:" This will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Research homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://microbiome.github.io/db" # the base hostname & protocol for your site
twitter_username: microbiome
github_username:  microbiome

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Adjunct Professor"
excerpt_separator: "<!--more-->"


# From http://tuxette.nathalievilla.org/?p=1426#more-1426
# Styles https://github.com/citation-style-language/styles
scholar:  
  style: _layouts/mycitationstyle.csl
  locale: en

  sort_by: year
  order: descending

  source: publications
  bibliography: lahti.bib
  bibliography_template: bibliography # from _layouts folder / or "{ reference }"

  replace_strings: true
  join_strings: true  

  details_dir:    bib
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
